apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmproject3.fullname" . }}
  namespace: helmproject
  labels:
    {{- include "helmproject3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "helmproject3.selectorLabels" . | nindent 4 }}
